<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="4" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-12T20:55:40 IST" name="Default Suite" finished-at="2023-08-12T20:56:10 IST" duration-ms="30623">
    <groups>
    </groups>
    <test started-at="2023-08-12T20:55:40 IST" name="project4" finished-at="2023-08-12T20:56:10 IST" duration-ms="30623">
      <class name="HardAssertionsExample">
        <test-method is-config="true" signature="beforeTestAnnot()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:55:40 IST" name="beforeTestAnnot" finished-at="2023-08-12T20:55:40 IST" duration-ms="530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTestAnnot -->
        <test-method is-config="true" signature="beforetestcase()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:55:40 IST" name="beforetestcase" finished-at="2023-08-12T20:55:44 IST" duration-ms="3966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetestcase -->
        <test-method signature="testcase1()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:55:44 IST" name="testcase1" finished-at="2023-08-12T20:55:53 IST" duration-ms="8977" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1 -->
        <test-method is-config="true" signature="aftertestcase()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:55:53 IST" name="aftertestcase" finished-at="2023-08-12T20:55:53 IST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertestcase -->
        <test-method is-config="true" signature="beforetestcase()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:55:53 IST" name="beforetestcase" finished-at="2023-08-12T20:55:55 IST" duration-ms="1945" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetestcase -->
        <test-method signature="testcase2()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:55:55 IST" name="testcase2" finished-at="2023-08-12T20:56:01 IST" duration-ms="5560" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[title of the page is not same/matches expected [google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: title of the page is not same/matches expected [google] but found [Google]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at HardAssertionsExample.testcase2(HardAssertionsExample.java:58)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2 -->
        <test-method is-config="true" signature="aftertestcase()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:56:01 IST" name="aftertestcase" finished-at="2023-08-12T20:56:02 IST" duration-ms="1084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertestcase -->
        <test-method is-config="true" signature="beforetestcase()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:56:02 IST" name="beforetestcase" finished-at="2023-08-12T20:56:04 IST" duration-ms="1759" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforetestcase -->
        <test-method signature="testcase4()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:56:04 IST" name="testcase4" finished-at="2023-08-12T20:56:09 IST" duration-ms="5329" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[title of the page is same/matches did not expect [Google] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: title of the page is same/matches did not expect [Google] but found [Google]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:1986)
at HardAssertionsExample.testcase4(HardAssertionsExample.java:83)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4 -->
        <test-method is-config="true" signature="aftertestcase()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:56:09 IST" name="aftertestcase" finished-at="2023-08-12T20:56:10 IST" duration-ms="401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftertestcase -->
        <test-method is-config="true" signature="afterTestAnnot()[pri:0, instance:HardAssertionsExample@428640fa]" started-at="2023-08-12T20:56:10 IST" name="afterTestAnnot" finished-at="2023-08-12T20:56:10 IST" duration-ms="736" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTestAnnot -->
      </class> <!-- HardAssertionsExample -->
    </test> <!-- project4 -->
  </suite> <!-- Default Suite -->
</testng-results>
